\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={800-171 Analysis},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{800-171 Analysis}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


\begin{document}
\maketitle

\subsection{Data Loading}\label{data-loading}

Loading the SP-800-171 excel file into R for analysis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Julia Smadja's working directory, what's in quotation marks must changed}
\NormalTok{Security_Requirements <-}\StringTok{ }\KeywordTok{read_excel}\NormalTok{(}\StringTok{"800-171 Appendix D.xlsx"}\NormalTok{) }
\KeywordTok{head}\NormalTok{(Security_Requirements)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
##   `SR Family` `SR Family Name` `Type of SR`  `SP 800-171` `SP 800-171 SR` 
##         <dbl> <chr>            <chr>         <chr>        <chr>           
## 1        3.01 ACCESS CONTROL   Basic Securi~ 3.1.1        Limit system ac~
## 2        3.01 ACCESS CONTROL   Basic Securi~ 3.1.2        Limit system ac~
## 3        3.01 ACCESS CONTROL   Basic Securi~ 3.1.1        Limit system ac~
## 4        3.01 ACCESS CONTROL   Basic Securi~ 3.1.2        Limit system ac~
## 5        3.01 ACCESS CONTROL   Basic Securi~ 3.1.1        Limit system ac~
## 6        3.01 ACCESS CONTROL   Basic Securi~ 3.1.2        Limit system ac~
## # ... with 5 more variables: `800-53 Family` <chr>, `NIST SP
## #   800-53` <chr>, `NIST SP 800-53 Relevant Security Controls` <chr>,
## #   `ISO/IEC 27001` <chr>, `ISO/IEC 27001 Relevant Security
## #   Controls` <chr>
\end{verbatim}

\subsection{Data Cleaning}\label{data-cleaning}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Security_Requirements <-}\StringTok{ }\NormalTok{Security_Requirements }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#renaming variables so there is no space}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\StringTok{`}\DataTypeTok{SR_Family}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{SR Family}\StringTok{`}\NormalTok{, }
         \StringTok{`}\DataTypeTok{SR_Family_Name}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{SR Family Name}\StringTok{`}\NormalTok{, }
         \StringTok{`}\DataTypeTok{Type_of_SR}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{Type of SR}\StringTok{`}\NormalTok{, }
         \StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{SP 800-171}\StringTok{`}\NormalTok{,}
         \StringTok{`}\DataTypeTok{SP_800-171_SR}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{SP 800-171 SR}\StringTok{`}\NormalTok{,}
         \StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{800-53 Family}\StringTok{`}\NormalTok{,}
         \StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{NIST SP 800-53}\StringTok{`}\NormalTok{, }
         \StringTok{`}\DataTypeTok{NIST_SP_800-53_Relevant_Security_Controls}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{NIST SP 800-53 Relevant Security Controls}\StringTok{`}\NormalTok{,}
         \StringTok{`}\DataTypeTok{ISO/IEC_27001_Relevant_Security_Controls}\StringTok{`}\NormalTok{ =}\StringTok{ `}\DataTypeTok{ISO/IEC 27001 Relevant Security Controls}\StringTok{`}\NormalTok{) }
  
  
\StringTok{`}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`}\NormalTok{ <-}\StringTok{ }\NormalTok{Security_Requirements }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(SR_Family, SR_Family_Name, }\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{, }\StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{, }\StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{distinct}\NormalTok{()}

\KeywordTok{head}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   SR_Family SR_Family_Name `SP_800-171` `800-53_Family` `NIST_SP_800-53`
##       <dbl> <chr>          <chr>        <chr>           <chr>           
## 1      3.01 ACCESS CONTROL 3.1.1        AC              AC-2-0          
## 2      3.01 ACCESS CONTROL 3.1.2        AC              AC-2-0          
## 3      3.01 ACCESS CONTROL 3.1.1        AC              AC-3-0          
## 4      3.01 ACCESS CONTROL 3.1.2        AC              AC-3-0          
## 5      3.01 ACCESS CONTROL 3.1.1        AC              AC-17-0         
## 6      3.01 ACCESS CONTROL 3.1.2        AC              AC-17-0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(`SP_800-171 Cleaned`)}
\end{Highlighting}
\end{Shaded}

\section{Data Analysis}\label{data-analysis}

The purpose of this analysis is to understand the different security
requirements (SP 800-171) and their families and their relationships
with the security controls in NIST Special Publication 800-53. An
additional visual analysis is done using Tableau for ease of
interpretation.

\textbf{Number of Security Requirement Families for SP-171 and their
names?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SRFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_SRFamily =} \KeywordTok{n_distinct}\NormalTok{(SR_Family))}

\KeywordTok{head}\NormalTok{(Count_SRFamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   count_SRFamily
##            <int>
## 1             14
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SRFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family, SR_Family_Name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SRFamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
## # Groups:   SR_Family [6]
##   SR_Family SR_Family_Name                   
##       <dbl> <chr>                            
## 1      3.01 ACCESS CONTROL                   
## 2      3.02 AWARENESS AND TRAINING           
## 3      3.03 AUDIT AND ACCOUNTABILITY         
## 4      3.04 CONFIGURATION MANAGEMENT         
## 5      3.05 IDENTIFICATION AND AUTHENTICATION
## 6      3.06 INCIDENT RESPONSE
\end{verbatim}

There are 14 security requirement families to protect the
confidentiality of CUI in nonfederal systems and organizations.

As the analysis moves forward, the analysis dives deeper into the
security requirements, how many there are and how they are related to
their families.

\textbf{Number of Security Requirement for SP-171 and their ``names''?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SR <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_SR =} \KeywordTok{n_distinct}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{))}

\KeywordTok{head}\NormalTok{(Count_SR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   count_SR
##      <int>
## 1      110
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SR <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 1
##   `SP_800-171`
##   <chr>       
## 1 3.1.1       
## 2 3.1.10      
## 3 3.1.11      
## 4 3.1.12      
## 5 3.1.13      
## 6 3.1.14
\end{verbatim}

There is a total of 110 security requirements within those families.

\textbf{Security Requirement families with the number of security
requirements (SP 800-171)?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SRFamily_SR <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_of_SP_800_171 =} \KeywordTok{n_distinct}\NormalTok{(SR_Family, }\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(count_of_SP_800_}\DecValTok{171}\NormalTok{ ))}

\KeywordTok{head}\NormalTok{(Count_SRFamily_SR)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   SR_Family count_of_SP_800_171
##       <dbl>               <int>
## 1      3.01                  22
## 2      3.13                  16
## 3      3.05                  11
## 4      3.03                   9
## 5      3.04                   9
## 6      3.08                   9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SRFamily_SR <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{names_of_SP_800_171 =} \KeywordTok{toString}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SRFamily_SR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   SR_Family names_of_SP_800_171                                           
##       <dbl> <chr>                                                         
## 1      3.01 3.1.1, 3.1.2, 3.1.1, 3.1.2, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5~
## 2      3.02 3.2.1, 3.2.2, 3.2.1, 3.2.2, 3.2.3                             
## 3      3.03 3.3.1, 3.3.2, 3.3.1, 3.3.2, 3.3.1, 3.3.2, 3.3.1, 3.3.2, 3.3.1~
## 4      3.04 3.4.1, 3.4.2, 3.4.1, 3.4.2, 3.4.1, 3.4.2, 3.4.1, 3.4.2, 3.4.3~
## 5      3.05 3.5.1, 3.5.2, 3.5.1, 3.5.2, 3.5.1, 3.5.2, 3.5.3, 3.5.3, 3.5.3~
## 6      3.06 3.6.1, 3.6.2, 3.6.1, 3.6.2, 3.6.1, 3.6.2, 3.6.1, 3.6.2, 3.6.1~
\end{verbatim}

From the 110 security requirements, the analysis looks into how they are
grouped within each security family. The security requirement family
with the largest amount of security requirements is 3.01 (ACCESS
CONTROL) with 22, followed by 3.13 (SYSTEM AND COMMUNICATIONS
PROTECTION) with 16 and 3.05 (IDENTIFICATION AND AUTHENTICATION) with
11.

The next steps in the analysis is to add the NIST 800-53 and understand
the mapping of the security requirements to the relevant security
controls (NIST 800-53).

\textbf{Security Requirement Families(SP 800-171) with the number of
security control families (SP 800-53) and the names of those security
control families.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SRFamily_SCFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_of_SP_800_53Families =} \KeywordTok{n_distinct}\NormalTok{(}\StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(count_of_SP_800_53Families))}

\NormalTok{Count_SRFamily_SCFamily}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 14 x 2
##    SR_Family count_of_SP_800_53Families
##        <dbl>                      <int>
##  1      3.08                          2
##  2      3.12                          2
##  3      3.13                          2
##  4      3.01                          1
##  5      3.02                          1
##  6      3.03                          1
##  7      3.04                          1
##  8      3.05                          1
##  9      3.06                          1
## 10      3.07                          1
## 11      3.09                          1
## 12      3.1                           1
## 13      3.11                          1
## 14      3.14                          1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SRFamily_SCFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{names_of_SP_800_53Families =} \KeywordTok{toString}\NormalTok{(}\KeywordTok{unique}\NormalTok{(}\StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SRFamily_SCFamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   SR_Family names_of_SP_800_53Families
##       <dbl> <chr>                     
## 1      3.01 AC                        
## 2      3.02 AT                        
## 3      3.03 AU                        
## 4      3.04 CM                        
## 5      3.05 IA                        
## 6      3.06 IR
\end{verbatim}

Within the security requirement families there are only three families
that have 2 security control families, 3.08, 3.12 and 3.13. All the
other families only have one security control family. 3.08 has CP and
MP, 3.12 has CA and PL, and 3.13 has SA and SC.

\textbf{Security Requirement Families (SP 800-171) with the number of
security controls (SP 800-53) and the names of those security controls.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SRFamily_SC <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_of_SP_800_53 =} \KeywordTok{n_distinct}\NormalTok{(}\StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(count_of_SP_800_}\DecValTok{53}\NormalTok{))}

\NormalTok{Count_SRFamily_SC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 14 x 2
##    SR_Family count_of_SP_800_53
##        <dbl>              <int>
##  1      3.01                 28
##  2      3.13                 16
##  3      3.03                 14
##  4      3.04                 13
##  5      3.05                 11
##  6      3.08                  9
##  7      3.06                  6
##  8      3.07                  6
##  9      3.1                   6
## 10      3.14                  5
## 11      3.12                  4
## 12      3.02                  3
## 13      3.09                  3
## 14      3.11                  3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SRFamily_SC <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SR_Family) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{names_of_SP_800_53 =} \KeywordTok{toString}\NormalTok{(}\KeywordTok{unique}\NormalTok{(}\StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SRFamily_SC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   SR_Family names_of_SP_800_53                                            
##       <dbl> <chr>                                                         
## 1      3.01 AC-2-0, AC-3-0, AC-17-0, AC-4-0, AC-5-0, AC-6-0, AC-6-1, AC-6~
## 2      3.02 AT-2-0, AT-3-0, AT-2-2                                        
## 3      3.03 AU-2-0, AU-3-0, AU-3-1, AU-6-0, AU-11-0, AU-12-0, AU-2-3, AU-~
## 4      3.04 CM-2-0, CM-6-0, CM-8-0, CM-8-1, CM-3-0, CM-4-0, CM-5-0, CM-7-~
## 5      3.05 IA-2-0, IA-3-0, IA-5-0, IA-2-1, IA-2-2, IA-2-3, IA-2-8, IA-2-~
## 6      3.06 IR-2-0, IR-4-0, IR-5-0, IR-6-0, IR-7-0, IR-3-0
\end{verbatim}

Within the Security Requirement families, 3.01 has the largest amount of
security controls with 28, followed by 3.13 with 16, 3.03 with 14, 3.04
with 13 and 3.05 with 11.

\textbf{Security Requirement (SP 800-171) with the number of security
control families (SP 800-53) and the names of those security control
families.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SR_SCFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_of_SP_800_53Families =} \KeywordTok{n_distinct}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{, }\StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(count_of_SP_800_53Families))}

\KeywordTok{head}\NormalTok{(Count_SR_SCFamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   `SP_800-171` count_of_SP_800_53Families
##   <chr>                             <int>
## 1 3.12.1                                2
## 2 3.12.2                                2
## 3 3.12.3                                2
## 4 3.12.4                                2
## 5 3.13.1                                2
## 6 3.13.2                                2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SR_SCFamily <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{names_of_SP_800_53Families =} \KeywordTok{toString}\NormalTok{(}\KeywordTok{unique}\NormalTok{(}\StringTok{`}\DataTypeTok{800-53_Family}\StringTok{`}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SR_SCFamily)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   `SP_800-171` names_of_SP_800_53Families
##   <chr>        <chr>                     
## 1 3.1.1        AC                        
## 2 3.1.10       AC                        
## 3 3.1.11       AC                        
## 4 3.1.12       AC                        
## 5 3.1.13       AC                        
## 6 3.1.14       AC
\end{verbatim}

There are 6 security requirements that have 2 different security
controls, 3.12.1, 3.12.2, 3.12.3, 3.12.4, 3.13.1 and 3.13.2.

\textbf{Security Requirement (SP 800-171) with the number of security
controls (SP 800-53) and the names of those security controls?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Count_SR_SC <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count_of_SP_800_53 =} \KeywordTok{n_distinct}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{,}\StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(count_of_SP_800_}\DecValTok{53}\NormalTok{))}

\KeywordTok{head}\NormalTok{(Count_SR_SC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   `SP_800-171` count_of_SP_800_53
##   <chr>                     <int>
## 1 3.3.1                         6
## 2 3.3.2                         6
## 3 3.6.1                         5
## 4 3.6.2                         5
## 5 3.10.1                        4
## 6 3.10.2                        4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Names_SR_SC <-}\StringTok{ `}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`} \OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171}\StringTok{`}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{names_of_SP_800_53 =} \KeywordTok{toString}\NormalTok{(}\StringTok{`}\DataTypeTok{NIST_SP_800-53}\StringTok{`}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}

\KeywordTok{head}\NormalTok{(Names_SR_SC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   `SP_800-171` names_of_SP_800_53     
##   <chr>        <chr>                  
## 1 3.1.1        AC-2-0, AC-3-0, AC-17-0
## 2 3.1.10       AC-11-0, AC-11-1       
## 3 3.1.11       AC-12-0                
## 4 3.1.12       AC-17-1                
## 5 3.1.13       AC-17-2                
## 6 3.1.14       AC-17-3
\end{verbatim}

The security requirements with the most number of security controls are
3.3.1 with 6 and 3.3.2 with 6, followd by 3.6.1 with 5 and 3.6.2 with 5.

\subsection{Exporting Data}\label{exporting-data}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{SP_800-171 Cleaned}\StringTok{`}\NormalTok{, }\StringTok{"SP_800-171 Cleaned.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SRFamily}\StringTok{`}\NormalTok{, }\StringTok{"Names_SRFamily.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SR}\StringTok{`}\NormalTok{, }\StringTok{"Names_SR.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Count_SRFamily_SR}\StringTok{`}\NormalTok{, }\StringTok{"Count_SRFamily_SR.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SRFamily_SR}\StringTok{`}\NormalTok{, }\StringTok{"Names_SRFamily_SR.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Count_SRFamily_SCFamily}\StringTok{`}\NormalTok{, }\StringTok{"Count_SRFamily_SCFamily.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SRFamily_SCFamily}\StringTok{`}\NormalTok{, }\StringTok{"Names_SRFamily_SCFamily.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Count_SRFamily_SC}\StringTok{`}\NormalTok{, }\StringTok{"Count_SRFamily_SC.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SRFamily_SC}\StringTok{`}\NormalTok{, }\StringTok{"Names_SRFamily_SC.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Count_SR_SCFamily}\StringTok{`}\NormalTok{, }\StringTok{"Count_SR_SCFamily.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SR_SCFamily}\StringTok{`}\NormalTok{, }\StringTok{"Names_SR_SCFamily.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Count_SR_SC}\StringTok{`}\NormalTok{, }\StringTok{"Count_SR_SC.csv"}\NormalTok{)}
\KeywordTok{write_csv}\NormalTok{(}\StringTok{`}\DataTypeTok{Names_SR_SC}\StringTok{`}\NormalTok{, }\StringTok{"Names_SR_SC.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

After exporting these excel files, combine these 13 different excel
workbooks into the same workbook, SP 800-171 Analysis, with 13 different
worksheets.\\
Combine the Count\_SR\_SC and Names\_SR\_SC into the same sheet and
Count\_SRFamily\_SR and Names\_SRFamily\_SR. Add the original SP 800-171
data set to the workbook, SP 800-171 Analysis.

A visual analysis is done with Tableau.


\end{document}
